language: ruby
rvm:
  - 2.7.0
before_install:
  - mv config/secrets-example.yml config/secrets.yml
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
  - bundle exec rspec spec/services/pill_notification_service_spec.rb:31
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
