language: ruby
rvm:
  - 2.7.0
env:
  - RUBYOPT='-W:no-deprecated -W:no-experimental'
  - RAILS_ENv=test
before_install:
  - mv config/secrets-example.yml config/secrets.yml
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
  - bundle exec rspec spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
