default: &default
  bugsnag_api_key: ''
  attr_encrypted_key: 'c866503259f66e11bf5a038f354924d4'
  salt: 'test'
  telegram:
    bot: ''

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

test:
  <<: *default
